// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eipfrvrehkxdlvpfcakq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcGZydnJlaGt4ZGx2cGZjYWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTg1MDYsImV4cCI6MjA4NTg5NDUwNn0.I8OEDXnYaFjLqG0MgDTspTFb0hGuv5LZFBlPzVD2VWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});